name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      package_to_install:
        description: 'Debian package name to install (leave empty for none)'
        required: false
        default: 'curl'
        type: string
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag cc-custom-images:$(date +%s) \
          --build-arg EXTRA_PACKAGES="${{ github.event.inputs.package_to_install }}"
